name: mobileapp_ui
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  provider: ^6.0.0
  google_fonts: ^6.2.0
  shared_preferences: ^2.2.3
  animated_notch_bottom_bar: ^1.0.3
  page_transition: ^2.1.0
  cached_network_image: ^3.3.1
  image_picker: ^1.2.1
  fl_chart: ^0.66.0

 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


